### ISSUE TITLE
Milestone 2 feedback: 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-solo_118#2]
Must fix: 

- [ ] importing scripts from project functions is not working, should be fixed
- [ ] Task 5: what are the research questions? 
- [ ] Task 5: what are the conclusions/observations?
- [ ] Add units to the graphs 

Optional, fix if there is time: 
- [ ] format the ipynb files using markdown in order to make them easier to read
